# Generated by Django 5.0.7 on 2024-07-29 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0004_remove_post_subscribers_category_чsubscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='чsubscribers',
            new_name='subscribers',
        ),
    ]
